name: C Project Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: List C files before compiling
        run: find . -type f -name "*.c" ! -path "*/screenshots/*"

      - name: Find and Compile C Code
        run:  find . -type f -name "*.c" ! -path "*/screenshots/*" -exec gcc -o {}.out {} -lm \;

      - name: List Compiled Files
        run: find . -type f -name "*.out"

      - name: Upload Generated Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-binaries
          path: "*.out"