name: Handle Release

on:
  release:
    types: [created]

jobs:


  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Download artifacts from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: release-artifacts
          path: ./artifacts

      - name: Upload artifacts to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: find . -type f -name "*.out"
          token: ${{ secrets.GITHUB_TOKEN }}